# Generated by Django 4.2.6 on 2023-11-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbre', '0002_alter_personne_mere_alter_personne_pere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='sexe',
            field=models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=40),
        ),
    ]
